import { type NextPage } from "next";
import Head from "next/head";

import { About } from "../components/about";
import AppLayout from "../components/Layout/appLayout";

const Project: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bang | Ani</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <main>
          <div>
            <div>
              <h1>Projects </h1>
              <blockquote>
                <p>I'll be documenting personal projects here soon™.</p>
              </blockquote>
            </div>
          </div>
        </main>
      </AppLayout>
    </>
  );
};

export default Project;
